---
title: "Poder de Estimacion"
author: "Nacho Borba"
date: "7/6/2021"
output:
  html_document:
    number_sections: no
  pdf_document: default
---

# Analisis por tratamiento

```{r}
rm(list=ls())
```

```{r}
power_calculator <- function(mu_t, mu_c, sigma, alpha=0.05, N){ 
  lowertail <- (abs(mu_t - mu_c)*sqrt(N))/(2*sigma) 
  uppertail <- -1*lowertail 
  beta <- pnorm(lowertail- qnorm(1-alpha/2), lower.tail=TRUE) + 1- pnorm(uppertail- qnorm(1-alpha/2), lower.tail=FALSE) 
  return(beta) 
}
```

```{r}
possible.ns <- seq(from=100, to=5000, by=50)     # The sample sizes we'll be considering
powers <- rep(NA, length(possible.ns))           # Empty object to collect simulation estimates
alpha <- 0.05                                    # Standard significance level
sims <- 1000                                     # Number of simulations to conduct for each N
```

Para T1 - Cannabis

```{r}
#### Outer loop to vary the number of subjects ####
for (j in 1:length(possible.ns)){
  N <- possible.ns[j]                              # Pick the jth value for N
  
  significant.experiments <- rep(NA, sims)         # Empty object to count significant experiments
  
  #### Inner loop to conduct experiments "sims" times over for each N ####
  for (i in 1:sims){
    Y0 <-  rnorm(n=N, mean=2.6, sd=10)            # control potential outcome
    tau <- 3                                      # Hypothesize treatment effect
    Y1 <- Y0 + tau                                # treatment potential outcome
    Z.sim <- rbinom(n=N, size=1, prob=.25)        # Do a random assignment 
    Y.sim <- Y1*Z.sim + Y0*(1-Z.sim)              # Reveal outcomes according to assignment
    fit.sim <- lm(Y.sim ~ Z.sim)                  # Do analysis (Simple regression)
    p.T1 <- summary(fit.sim)$coefficients[2,4]    # Extract p-values
    significant.experiments[i] <- (p.T1 <= alpha) # Determine significance according to p <= 0.05
  }
  
  powers[j] <- mean(significant.experiments)       # store average success rate (power) for each N
}

plot(possible.ns, powers, ylim=c(0,1))
abline(.8, 0, col="red")
```

Para T2 - Pasta base

```{r}
#### Outer loop to vary the number of subjects ####
for (j in 1:length(possible.ns)){
  N <- possible.ns[j]                              # Pick the jth value for N
  
  significant.experiments <- rep(NA, sims)         # Empty object to count significant experiments
  
  #### Inner loop to conduct experiments "sims" times over for each N ####
  for (i in 1:sims){
    Y0 <-  rnorm(n=N, mean=2.16, sd=10)           # control potential outcome
    tau <- 4.5                                    # Hypothesize treatment effect
    Y1 <- Y0 + tau                                # treatment potential outcome
    Z.sim <- rbinom(n=N, size=1, prob=.25)        # Do a random assignment
    Y.sim <- Y1*Z.sim + Y0*(1-Z.sim)              # Reveal outcomes according to assignment
    fit.sim <- lm(Y.sim ~ Z.sim)                  # Do analysis (Simple regression)
    p.T2 <- summary(fit.sim)$coefficients[2,4]    # Extract p-values
    significant.experiments[i] <- (p.T2 <= alpha) # Determine significance according to p <= 0.05
  }
  
  powers[j] <- mean(significant.experiments)       # store average success rate (power) for each N
}

plot(possible.ns, powers, ylim=c(0,1))
abline(.8, 0, col="red")
```

Para T3 - Alcohol

```{r}
#### Outer loop to vary the number of subjects ####
for (j in 1:length(possible.ns)){
  N <- possible.ns[j]                              # Pick the jth value for N
  
  significant.experiments <- rep(NA, sims)         # Empty object to count significant experiments
  
  #### Inner loop to conduct experiments "sims" times over for each N ####
  for (i in 1:sims){
    Y0 <-  rnorm(n=N, mean=3.16, sd=10)            # control potential outcome
    tau <- 1.5                                     # Hypothesize treatment effect
    Y1 <- Y0 + tau                                 # treatment potential outcome
    Z.sim <- rbinom(n=N, size=1, prob=.25)         # Do a random assignment
    Y.sim <- Y1*Z.sim + Y0*(1-Z.sim)               # Reveal outcomes according to assignment
    fit.sim <- lm(Y.sim ~ Z.sim)                   # Do analysis (Simple regression)
    p.T3 <- summary(fit.sim)$coefficients[2,4]     # Extract p-values
    significant.experiments[i] <- (p.T3 <= alpha)  # Determine significance according to p <= 0.05
  }
  
  powers[j] <- mean(significant.experiments)       # store average success rate (power) for each N
}

plot(possible.ns, powers, ylim=c(0,1))
abline(.8, 0, col="red")
```

Para T4 - Tabaco

```{r}
#### Outer loop to vary the number of subjects ####
for (j in 1:length(possible.ns)){
  N <- possible.ns[j]                              # Pick the jth value for N
  
  significant.experiments <- rep(NA, sims)         # Empty object to count significant experiments
  
  #### Inner loop to conduct experiments "sims" times over for each N ####
  for (i in 1:sims){
    Y0 <-  rnorm(n=N, mean=3, sd=10)               # control potential outcome
    tau <- 2                                       # Hypothesize treatment effect
    Y1 <- Y0 + tau                                 # treatment potential outcome
    Z.sim <- rbinom(n=N, size=1, prob=.25)         # Do a random assignment
    Y.sim <- Y1*Z.sim + Y0*(1-Z.sim)               # Reveal outcomes according to assignment
    fit.sim <- lm(Y.sim ~ Z.sim)                   # Do analysis (Simple regression)
    p.T4 <- summary(fit.sim)$coefficients[2,4]     # Extract p-values
    significant.experiments[i] <- (p.T4 <= alpha)  # Determine significance according to p <= 0.05
  }
  
  powers[j] <- mean(significant.experiments)       # store average success rate (power) for each N
}

plot(possible.ns, powers, ylim=c(0,1))
abline(.8, 0, col="red")
```


Ajusto comparación por Bonferroni

```{r}
pvalues <- c(p.T1, p.T2, p.T3, p.T4)
pvalues
```

```{r}
p.adjust(pvalues, method = "bonferroni")
```



# Power analysis for multiple treatments

```{r}
rm(list=ls())
```

```{r}
#install.packages("randomizr")
library(randomizr)    # randomizr package for complete random assignment
```

```{r}
possible.ns <- seq(from=100, to=5000, by=50)
power.atleastone <- rep(NA, length(possible.ns))
power.bothtreatments <- rep(NA, length(possible.ns))
power.fullranking <- rep(NA, length(possible.ns))
alpha <- 0.1  #(one-tailed test at .05 level)
sims <- 1000
```

Outer loop to vary the number of subjects

```{r}
for (j in 1:length(possible.ns)){
  N <- possible.ns[j]
  p.T1vsT2 <- rep(NA, sims)
  p.T1vsT3 <- rep(NA, sims)
  p.T1vsT4 <- rep(NA, sims)
  p.T2vsT3 <- rep(NA, sims)
  p.T2vsT4 <- rep(NA, sims)
  p.T3vsT4 <- rep(NA, sims)
  c.T1vsT2 <- rep(NA, sims)
  c.T1vsT3 <- rep(NA, sims)
  c.T1vsT4 <- rep(NA, sims)
  c.T2vsT3 <- rep(NA, sims)
  c.T2vsT4 <- rep(NA, sims)
  c.T3vsT4 <- rep(NA, sims)
  
  #### Inner loop to conduct experiments "sims" times over for each N ####
  for (i in 1:sims){
    Y1 <- rnorm(n=N, mean=3, sd=10)
    Y2 <- rnorm(n=N, mean=4.5, sd=10)
    Y3 <- rnorm(n=N, mean=1.5, sd=10)
    Y4 <- rnorm(n=N, mean=2, sd=10)
    Z.sim <- complete_ra(N=N, num_arms=4)
    Y.sim <- Y1*(Z.sim=="T1") + Y2*(Z.sim=="T2") + Y3*(Z.sim=="T3") + Y4*(Z.sim=="T4")
    frame.sim <- data.frame(Y.sim, Z.sim)
    fit.T1vsT2.sim <- lm(Y.sim ~ Z.sim=="T1", data=subset(frame.sim, Z.sim!="T3" & Z.sim!="T4"))
    fit.T1vsT3.sim <- lm(Y.sim ~ Z.sim=="T1", data=subset(frame.sim, Z.sim!="T2" & Z.sim!="T4"))
    fit.T1vsT4.sim <- lm(Y.sim ~ Z.sim=="T1", data=subset(frame.sim, Z.sim!="T2" & Z.sim!="T3"))
    fit.T2vsT3.sim <- lm(Y.sim ~ Z.sim=="T2", data=subset(frame.sim, Z.sim!="T1" & Z.sim!="T4"))
    fit.T2vsT4.sim <- lm(Y.sim ~ Z.sim=="T2", data=subset(frame.sim, Z.sim!="T1" & Z.sim!="T3"))
    fit.T3vsT4.sim <- lm(Y.sim ~ Z.sim=="T3", data=subset(frame.sim, Z.sim!="T1" & Z.sim!="T2"))
    
    ### Need to capture coefficients and pvalues (one-tailed tests, so signs are important)
    fit.T1vsT2.sim[i] <- summary(fit.T1vsT2.sim)$coefficients[2,4]
    fit.T1vsT3.sim[i] <- summary(fit.T1vsT3.sim)$coefficients[2,4]
    fit.T1vsT4.sim[i] <- summary(fit.T1vsT4.sim)$coefficients[2,4]
    fit.T2vsT3.sim[i] <- summary(fit.T2vsT3.sim)$coefficients[2,4]
    fit.T2vsT4.sim[i] <- summary(fit.T2vsT4.sim)$coefficients[2,4]
    fit.T3vsT4.sim[i] <- summary(fit.T3vsT4.sim)$coefficients[2,4]
  }
  power.atleastone[j] <- mean(c.T1vsT2 >0 &	c.T1vsT3 >0 & c.T1vsT4 >0 &	c.T2vsT3 >0 &	c.T2vsT4 >0 & c.T3vsT4 >0 &
                                (p.T1vsT2 < alpha/2 |	p.T1vsT3 < alpha/2 | p.T1vsT4 < alpha/2 | p.T2vsT3 < alpha/2 | p.T2vsT4 < alpha/2 | 
                                   p.T3vsT4 < alpha/2))
  power.bothtreatments[j] <-mean(c.T1vsT2 >0 &	c.T1vsT3 >0 & c.T1vsT4 >0 &	c.T2vsT3 >0 &	c.T2vsT4 >0 & c.T3vsT4 >0 &
                                (p.T1vsT2 < alpha/2 |	p.T1vsT3 < alpha/2 | p.T1vsT4 < alpha/2 | p.T2vsT3 < alpha/2 | p.T2vsT4 < alpha/2 | 
                                   p.T3vsT4 < alpha/2))
  power.fullranking[j] <- mean(c.T1vsT2 >0 &	c.T1vsT3 >0 & c.T1vsT4 >0 &	c.T2vsT3 >0 &	c.T2vsT4 >0 & c.T3vsT4 >0 &
                              (p.T1vsT2 < alpha/2 |	p.T1vsT3 < alpha/2 | p.T1vsT4 < alpha/2 | p.T2vsT3 < alpha/2 | p.T2vsT4 < alpha/2 | 
                                   p.T3vsT4 < alpha/2))
  print(j)
}

plot(possible.ns, power.atleastone, ylim=c(0,1))
points(possible.ns, power.bothtreatments, col="red")
points(possible.ns, power.fullranking, col="blue")
```


